---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DDenry.
--- DateTime: 2018/7/23 17:39
---

local CameraDevice = CS.Vuforia.CameraDevice
local yield_return = (require 'cs_coroutine').yield_return

local COROUTINE_CAMERA_AUTOFOCUS

function onenable()
    print("Camera_AutoFocus Enable!")
    --回收垃圾
    collectgarbage("collect")

    --
    COROUTINE_CAMERA_AUTOFOCUS = coroutine.create(function(state)
        while state do
            print("The device is trying 2 focus!")
            --设置不同模式进行自动对焦
            if CameraDevice.Instance:SetFocusMode(CameraDevice.FocusMode.FOCUS_MODE_NORMAL) then
            elseif CameraDevice.Instance:SetFocusMode(CameraDevice.FocusMode.FOCUS_MODE_TRIGGERAUTO) then
            elseif CameraDevice.Instance:SetFocusMode(CameraDevice.FocusMode.FOCUS_MODE_CONTINUOUSAUTO) then
            elseif CameraDevice.Instance:SetFocusMode(CameraDevice.FocusMode.FOCUS_MODE_INFINITY) then
            elseif CameraDevice.Instance:SetFocusMode(CameraDevice.FocusMode.FOCUS_MODE_MACRO) then
            else
                print("The device cannot focus!")
            end
            yield_return(CS.UnityEngine.WaitForSeconds(1.0))

            --获取传值
            state = coroutine.yield()
        end
    end)

    assert(coroutine.resume(coroutine.create(function()
        repeat
            if coroutine.status(COROUTINE_CAMERA_AUTOFOCUS) == "suspended" then
                assert(coroutine.resume(COROUTINE_CAMERA_AUTOFOCUS, true))
                yield_return(CS.UnityEngine.WaitForSeconds(3.0))
            end
        until COROUTINE_CAMERA_AUTOFOCUS == nil
    end)))
end

function start()
    --CS.Vuforia.CameraDeviceCameraDevice.Instance.GetCameraFieldOfViewRads
end

function update()

end

function ondisable()
    print("Camera_AutoFocus Disable!")
    --
    if COROUTINE_CAMERA_AUTOFOCUS ~= nil then
        assert(coroutine.resume(coroutine.create(function()
            assert(coroutine.resume(COROUTINE_CAMERA_AUTOFOCUS, false))
        end)))
    end
    --
    COROUTINE_CAMERA_AUTOFOCUS = nil
    --回收垃圾
    collectgarbage("collect")
end

function ondestroy()
    --回收垃圾
    collectgarbage("collect")
end