---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DDenry.
--- DateTime: 2019/11/8 15:21
---

local yield_return = (require 'cs_coroutine').yield_return

local audioSource, animator

local audioLength

local Confirm, Cancel, Audio, Animator, OnceMore, Exit, ScreenShot

local lyricText

local mediaStruct = {
    from = 0, to = 0, actionId = 1
}

Audio = self.transform:Find("AudioSource").gameObject
Animator = self.transform:Find("test01").gameObject
OnceMore = self.transform:Find("Canvas/OnceMore").gameObject
Confirm = self.transform:Find("Canvas/OnceMore/Bottom/Confirm")
Cancel = self.transform:Find("Canvas/OnceMore/Bottom/Cancel")
ScreenShot = self.transform:Find("Canvas/ScreenShot")
Exit = self.transform:Find("Canvas/Exit").gameObject

function mediaStruct:new(from, to, actionId)

    self.from = from
    self.to = to
    self.actionId = actionId

    local o = {
        from = self.from,
        to = self.to,
        actionId = self.actionId
    }

    --元表保护
    self.__metatable = "Sorry, u cannot do this!"

    --元表
    setmetatable(o, self)
    self.__index = self

    return o
end

--
local mediaGroup = {
    mediaStruct:new(0, 9.5, 6),
    mediaStruct:new(10, 13, 0),
    mediaStruct:new(14, 20, 2),
    mediaStruct:new(20.3, 25.5, 5),
    mediaStruct:new(25.8, 31, 1),
    mediaStruct:new(31.3, 36.7, 6),
    mediaStruct:new(37, 42.5, 4),
    mediaStruct:new(42.8, 48, 3),
    mediaStruct:new(48.3, 53.6, 7),
    mediaStruct:new(54, 58.8, 2),
    mediaStruct:new(59, 64, 1),
    mediaStruct:new(64.3, 69.5, 4),
    mediaStruct:new(70, 75, 7),
    mediaStruct:new(75.5, 78, 6)
}

local lyricStruct = {
    from = 0, to = 0, content = ""
}

function lyricStruct:new(from, to, content)
    self.from = from
    self.to = to
    self.content = content

    local o = {
        from = self.from,
        to = self.to,
        content = self.content
    }

    --元表保护
    self.__metatable = "Sorry, u cannot do this!"

    --元表
    setmetatable(o, self)
    self.__index = self

    return o
end

local lyrics = {
    lyricStruct:new(14, 20, "荤素搭配多喝水，营养均衡身体棒"),
    lyricStruct:new(20.3, 25.5, "勤洗小手多运动，日常消毒要做透"),
    lyricStruct:new(25.8, 31, "毛巾澡盆不共用，保持卫生区别开"),
    lyricStruct:new(31.3, 36.7, "喷嚏咳嗽捂口鼻，疾病传播就没招"),
    lyricStruct:new(37, 42.5, "人多扎堆空气糟，尽量别去凑热闹"),
    lyricStruct:new(42.8, 48, "室内开窗常换气，细菌病毒无处去"),
    lyricStruct:new(48.3, 53.6, "睡眠充足个子高，劳逸结合最最好"),
    lyricStruct:new(54, 58.8, "天气温度多注意，添减衣物要及时"),
    lyricStruct:new(59, 64, "提高免疫最重要，身强体壮又聪明"),
    lyricStruct:new(64.3, 69.5, "连续发烧上医院，疾病治疗要趁早"),
    lyricStruct:new(70, 75, "身体健康是个宝，开心欢笑不会少")
}

audioSource = Audio:GetComponent("AudioSource")
audioLength = audioSource.clip.length

animator = Animator:GetComponent("Animator")

lyricText = self.transform:Find("Canvas/LyricText"):GetComponent("Text")

function onenable()
    begin()
end

function start()

    ScreenShot:GetComponent("Button").onClick:AddListener(function()
        CS.UnityEngine.ScreenCapture.CaptureScreenshot(CS.System.DateTime.Now:ToFileTimeUtc() .. ".jpg")
    end)

    Confirm:GetComponent("Button").onClick:AddListener(function()
        begin()
    end)

    Cancel:GetComponent("Button").onClick:AddListener(function()
        exit()
    end)

    Exit:GetComponent("Button").onClick:AddListener(function()
        exit()
    end)
end

function exit()
    self.gameObject:SetActive(false)
    CS.UnityEngine.GameObject.Find("Configs/DataSetLoader"):GetComponent(typeof(CS.EzComponents.Vuforia.DataSetLoader)):ActiveDataSet()
end

function begin()

    OnceMore:SetActive(false)

    audioSource:Play()

    animator.enabled = true

    animator:Play("-1")

    assert(coroutine.resume(coroutine.create(function()
        while (audioSource.isPlaying) do

            local duration = 0.5

            for i, media in ipairs(mediaGroup) do
                if audioSource.time + 0.3 > media['from'] and audioSource.time + 0.3 < media['to'] then
                    animator:Play("-1")
                    animator:Update(1)
                    yield_return(1)
                    animator:Play(tostring(media['actionId']))
                    duration = tonumber(media['to'] - media['from'])
                end
            end

            yield_return(CS.UnityEngine.WaitForSeconds(duration + 0.05))
        end
    end)))

    assert(coroutine.resume(coroutine.create(function()
        while (audioSource.isPlaying) do

            local duration = 0.5

            lyricText.text = ""

            for i, lyric in ipairs(lyrics) do
                if audioSource.time > lyric['from'] and audioSource.time < lyric['to'] then
                    lyricText.text = lyric['content']
                    duration = tonumber(lyric['to'] - lyric['from'])
                end
            end

            yield_return(CS.UnityEngine.WaitForSeconds(duration + 0.05))
        end
    end)))

end

function update()
    if audioSource ~= nil and audioSource.isPlaying then
        if audioLength - audioSource.time < 0.5 then
            print("Audio played once completely!")
            animator:Play(0)
            finish()
        end
    end
end

function finish()
    audioSource:Stop()
    OnceMore:SetActive(true)
    animator.enabled = false
end